<a href="https://colab.research.google.com/github/Ruthnguli/cells_geo/blob/main/Moringa_Data_Science_Prep_W3_Independent_Project_2021_09_Ruth_Nguli_Python_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Moringa Data Science: Prep W3 Independent Project Python Notebook

In [ ]:
#we import pandas library to working directory
import pandas as pd
#Also import numpy library
import numpy as np

In [38]:
#loading data our cells geo discription dataset
df = pd.read_excel('cells_geo_description.xlsx')
df

     Column name                                        Description  Format
0         VILLES                                               City  String
1         STATUS                                  In Service or not  String
2   LOCALISATION                                  in ABIDJAN or not  String
3     DECOUPZONE                                  Geographical Zone  String
4       ZONENAME                                       Name of Zone  String
5      LONGITUDE                                          Longitude   Float
6       LATITUDE                                           Latitude   Float
7         REGION                                             Region  String
8           AREA                                               Area  String
9        CELL_ID                                     ID of the cell  String
10     SITE_CODE  Site (there are several cells per site, severa...  String

In [84]:
#loading data our csv dataset from url = https://raw.githubusercontent.com/Ruthnguli/cells_geo/main/cells_geo.csv
#create DataFrame from th cells_geo url
url = "https://raw.githubusercontent.com/Ruthnguli/cells_geo/main/cells_geo.csv"
df = pd.read_csv(url,  delimiter = ';')
#viewing the first 10 rows
df.head(10)

   Unnamed: 0    VILLES      STATUS  ... AREA     CELL_ID   SITE_CODE
0           0    ADJAME  In Service  ...  NaN  fbb2e75af3  0bb492ef17
1           1    ADJAME  In Service  ...  NaN  1502501d78  0bb492ef17
2           2    ADJAME  In Service  ...  NaN  0c2e182a0c  0bb492ef17
3           3   ASSINIE  In Service  ...  NaN  69bdfc69fd  8a1e6ce31f
4           4   ASSINIE  In Service  ...  NaN  7a1029d2ab  8a1e6ce31f
5           5   ASSINIE  In Service  ...  NaN  0b4f56438f  8a1e6ce31f
6           6  KRIKOREA  In Service  ...  NaN  041d2504f5  260dbfedc5
7           7     ABOBO  In Service  ...  NaN  a70c1d263b  56306cc7ca
8           8     ABOBO  In Service  ...  NaN  e2d04ea883  56306cc7ca
9           9     ABOBO         NaN  ...  NaN  ee224cd27e  56306cc7ca

[10 rows x 12 columns]

In [85]:

# we change the column Villes which is city as per the discription to display a new name City for farmiliarity
df_new = df.rename(columns={'VILLES': 'CITY', 'SITE_CODE': 'SITE_ID'})
df_new

      Unnamed: 0      CITY      STATUS  ...          AREA     CELL_ID     SITE_ID
0              0    ADJAME  In Service  ...           NaN  fbb2e75af3  0bb492ef17
1              1    ADJAME  In Service  ...           NaN  1502501d78  0bb492ef17
2              2    ADJAME  In Service  ...           NaN  0c2e182a0c  0bb492ef17
3              3   ASSINIE  In Service  ...           NaN  69bdfc69fd  8a1e6ce31f
4              4   ASSINIE  In Service  ...           NaN  7a1029d2ab  8a1e6ce31f
...          ...       ...         ...  ...           ...         ...         ...
3969        3969  ZUENOULA  In Service  ...  CENTRE NORTH  1cfc2d7ab1  f91ed8d2e9
3970        3970  ZUENOULA  In Service  ...  CENTRE NORTH  3ae1708153  f91ed8d2e9
3971        3971  ZUENOULA  In Service  ...  CENTRE NORTH  cb71f8a29c  61bee9c70c
3972        3972  ZUENOULA  In Service  ...  CENTRE NORTH  d4a6a0b645  61bee9c70c
3973        3973  ZUENOULA  In Service  ...  CENTRE NORTH  f9f3e42589  61bee9c70c

[3974 rows x 12 columns]

In [96]:
#Find out the unique values of city columns
list(df_new['CITY'].unique())

['ADJAME',
 'ASSINIE',
 'KRIKOREA',
 'ABOBO',
 'BINGERVILLE',
 'PLATEAU',
 'DALOA',
 'ABENGOUROU',
 'ATTECOUBE',
 'ABOISSO COMOE',
 'ABOISSO',
 'BONGOUANOU',
 'ABONGOUA',
 'ABOUDEKOUASSIKRO',
 'ABRONAMOUE',
 'YOPOUGON',
 'ADAOU',
 'ADDAH',
 'ADEBEM',
 'ADIAKE',
 'ADJAMENE',
 'PORT-BOUET',
 'ADZOPE',
 'AFFERY',
 'COCODY',
 'AGBOVILLE',
 'AGNIBILEKRO',
 'AGONDA',
 'AGOU',
 'MARCORY',
 'AHIZABRO',
 'AHOUANOU',
 'BOUAKE',
 'AKOBOISSUE',
 'AKOUPE',
 'AKOUYAKRO',
 'AKRADJO',
 'KOUMASSI',
 'ALEPE',
 'ALERIA',
 'BAMORO',
 'ALLOKOI',
 'ANANDA',
 'ANDO',
 'ANDOKOKRENOU',
 'ANIANSUE',
 'ANOUMABA',
 'ANYAMA',
 'AOUNIANFOUTOU',
 'APPOISSO',
 'ARRAH',
 'ASSIKOI',
 'ASSUEFRY',
 'ATTIGUEHI',
 'ATTINGUIE',
 'ATTROBROU',
 'AYAME',
 'AYAPRIKRO',
 'AZAGUIE',
 'BACANDA',
 'BADIKAHA',
 'BAGOHOUO',
 'BAHOMPA',
 'BACOUBLY',
 'BALEKO',
 'SAN-PEDRO',
 'BANADJE',
 'BANANKORO',
 'BANDAKANY',
 'BANDIAHI',
 'BANGOLO',
 'BANIA',
 'BANTEAPLEU',
 'BAOUBLI',
 'YAMOUSSOUKRO',
 'GRAND-BASSAM',
 'BAYOTA',
 'BAZRA NATTIS',
 'BECEDIBRIGNAN',
 'BEDIALA',
 'BEKOUEFIN',
 'BENGASSOU',
 'BEOUE',
 'BEOUMI',
 'BETTIE',
 'BIANKOUMA',
 'BIANOUAN',
 'BIELOU-CARREFOUR',
 'BILIMONO',
 'BINAO',
 'BIN HOUNIEN',
 'BLAHOU',
 'BLANFLA',
 'DIANOUFLA',
 'BLE',
 'BLESSEGUE',
 'BLOLEQUIN',
 'BOCANDA',
 'BODO',
 'BODOKRO',
 'BOGUEDIA',
 'BOLI',
 'BONAHOUIN',
 'BONDOUKOU',
 'BONGO',
 'BONGUERA',
 'BONIEREDOUGOU',
 'BONIKRO',
 'BONON',
 'BONOUA',
 'BONOUFLA',
 'BOOKO',
 'BORON',
 'BOROTOU',
 'BOROTOUKRO',
 'BOTRO',
 'BOUADIKRO',
 'BOUAFLE',
 'BOUADOUGOU',
 'BOUAPE',
 'BOUGOU',
 'BOUNA',
 'BOUNAFLA',
 'BOUNDIALI',
 'BOZI',
 'BROBO',
 'BROFFOUEDOU',
 'BROFODOUME',
 'BROU AKPASSOU',
 'BUYO',
 'CECHI',
 'CHIEPO',
 'TREICHVILLE',
 'COLLINEKASSEREGUE',
 'KETEKRE',
 'DABADOUGOU',
 'DABAKALA',
 'DABOU',
 'DABOUYO',
 'DAGADJI',
 'DAGOUAHIO',
 'DAHIRI',
 'DAIRO/DIDIZO',
 'DAKPADOU',
 'DAME',
 'DANANE',
 'DANANON',
 'DANGUIRA',
 'DANIA',
 'DAOUKRO',
 'DASSIOKO',
 'DIABO',
 'DIAMARAKRO',
 'DIANGOKRO',
 'DIANRA',
 'DIANRAVILLAGE',
 'DIARABANA',
 'DIARAKRO',
 'DIAWALA',
 'DIDIEVI',
 'DIDOKO',
 'DIEGONEFLA',
 'DIEOUZON',
 'DIGNAGO',
 'DIKODOUGOU',
 'DIMBOKRO',
 'DIOULATIEDOUGOU',
 'DIVO',
 'DIVO PALMCI',
 'DJASSANOU',
 'DJEBONOUA',
 'DJEMISSIKRO',
 'DJENIDOUFLA',
 'DJIBROSSO',
 'DJI',
 'DJOUKOUYO',
 'DOKE',
 'DOROPO',
 'DOTENZIA',
 'DOUFREBO',
 'DOUGOUDOU SODEMI',
 'DOUGROUPALEGNOA',
 'DUEKOUE',
 'EBIKRO',
 'EHANIA',
 'ELLIBOU',
 'HIRE',
 'ETTROKRO',
 'ETUEBOUE',
 'FACOBLY',
 'FADYADOUGOU',
 'FEREDOUGOU',
 'FERKE',
 'FLAKIE',
 'FOUMBOLO',
 'FOUNGBESSO',
 'FRESCO',
 'FRONAN',
 'GABIADJI',
 'GADOUAN',
 'GAGNOA',
 'GAZIBOUO',
 'GBAGBAM',
 'GBAPLEU',
 'GRAND BEREBY',
 'GBELEBAN',
 'GBETEGUELA',
 'GBONNE',
 'GRAND LAHOU',
 'GLIGBEUADJI',
 'GNABOYA',
 'GNAGBODOUGNOA',
 'GNAMONO',
 'GNIPI',
 'GOHITAFLA',
 'GOMENEBERI',
 'GONATE',
 'GOULIA',
 'GRAND-ZATRY',
 'GROBIASSOUME',
 'GUEHIEBLY',
 'GUESSABO',
 'GUESSIGUIE',
 'GUEYO',
 'GUEZON',
 'GUEZON TAHOUAKE',
 'GUIBEROUA',
 'GUIEMBE',
 'GUIGLO',
 'GUINKIN',
 'GUINTEGUELA',
 'GUITRY',
 'HEREMANKONO',
 'HERMANKONONO/DIES',
 'IBOGUHE',
 'IDEFOR',
 'ILESBOULEY',
 'IROBO',
 'ISSIA',
 'ITTY',
 'JACQUEVILLE',
 'KAHANSO',
 'KAKOHORO',
 'KALAKALA',
 'KAMELE',
 'KAMORO',
 'KANAKONO',
 'KANI',
 'KANOROBA',
 'KANZRA',
 'KASSERE',
 'KATIOLA',
 'KEIBLA',
 'KETESSO',
 'KETRO BASSAM',
 'KIMBIRILA NORD',
 'KIMBIRILA SUD',
 'KLOTOU',
 'KOBEDAIGOURE',
 'KODIOSSOU',
 'KODJINAN',
 'KOFFI AMONKRO',
 'KOKOUMBO',
 'KOLIA',
 'KOMBORODOUGOU',
 'KONAHIRI',
 'KONEDOUGOU',
 'KONG',
 'KONGASSO',
 'KONI',
 'KONONFLA',
 'KONTROU',
 'KOONAN',
 'KOREA',
 'KORHOGO',
 'KORO',
 'KOSSANDJI',
 'KOSSOU',
 'KOTABLEA',
 'KOTOUBA',
 'KOTOULA',
 'KOUASSIDATEKRO',
 'KOUASSIKOUASSIKRO',
 'KOUEGO',
 'KOUIBLY',
 'KOUN-FAO',
 'KOUNTIGUISSO',
 'KOUTO',
 'KOYOKRO',
 'KPAPEKOU',
 'KPOUEBO',
 'KRINJABO',
 'KRIZABAHIO',
 'LAFOKPOKAHA',
 'DEDI',
 'LAHOUDIBA',
 'LAKOTA',
 'LAMADOUGOU',
 'LAOGUIE',
 'LARABIA',
 'LATAHA',
 'LUEHOUAN',
 'LOGBOVILLE',
 'LOGOUALE',
 'LOUGBONON',
 'LOVIGUE',
 'LUENOUFLA',
 'MADINANI',
 'MAFERE',
 'MAHAPLEU',
 'MAMA',
 'MAN',
 'MANKONO',
 'MANZANOUAN',
 'MARABADIASSA',
 'MARANDALA',
 'MASSALA',
 'MAYO',
 "M'BAHIAKRO",
 'MBATTO',
 'MBENGUE',
 'MBONOUA',
 'MBORLA',
 'MBROU',
 'MEADJI',
 'MEMNI',
 'MINIGNAN',
 'MINORE',
 'MOAPE',
 'MONTCOUPE',
 'MORONDO',
 'MORONOU',
 'MOUSSADOUGOU',
 'NAFALA',
 'NAMASSI',
 'NAMBENGUE',
 'KARAKORO',
 'NANIEFONGO',
 'NAPIE',
 'NASSIAN',
 'KOUASSIA-NIAGUNI',
 "N'DEBO",
 "N'DOUCI",
 'NDOUKAHAKRO',
 'NEKA',
 'NGATTADOLIKRO',
 "N'GATTAKRO",
 'NGUINOU',
 'NIABABLY',
 'NIABLE',
 'NIAKARA',
 'TOUIH',
 'NIAMANA',
 'NIAMBEZARIA',
 'NIANDA',
 'NIANGBO',
 'NIDROU',
 'NIOFOIN',
 'NOE',
 'NOUAMOU',
 'NOUKPOUDOU',
 'NOUVELLEOUSROU',
 "N'ZECREZESSOU",
 'NZIANOUA',
 "N'ZIKRO",
 'ODIENNE',
 'OGHLAPO',
 'OKROUYO',
 'ORESS KROBOU',
 'OTTAWA',
 'OUALEBO',
 'OUANGOLO',
 'OUANINOU',
 'OUATTARADOUGOU',
 'OUELLE',
 'OUME',
 'OUNADIEKAHA',
 'OUPOYO',
 'OURAGAHIO',
 'PAKAOUBO',
 'BLIDOUBA',
 'IBOKE',
 'PARA',
 'PEHE',
 'PELEZI',
 'PETIONARA',
 'PETIT YAPO',
 'PINHOU',
 'PINHOU KOULOUAN',
 'PODIAGOUINE',
 'POGO',
 'PONANGUIGLO',
 'PRIKRO',
 'POPREAGUI',
 'SIPILOU',
 'RAPIDES GRAH',
 'RAVIART',
 'RUBINO',
 'SAFCO',
 'SAGO',
 'SAHUE',
 'SAIOUA',
 'SAKAHOUO',
 'SAKASSOU',
 'SAMANGO',
 'SAMATIGUILA',
 'SAMO',
 'SANANFEREDOUGOU',
 'SANDEGUE',
 'SANGOUINE',
 'SANKADIOKRO',
 'SAPLI',
 'SARAKADJI',
 'SARHALA',
 'SASSANDRA',
 'SATIKRAN',
 'SEGUELA',
 'SEGUELON',
 'SEMIEN',
 'SERHIO',
 'SEYDOUGOU',
 'GOUMERE',
 'SIANA',
 'SIEMPURGO',
 'SIENSOBA',
 'SIFIE',
 'SIKENSI',
 'SINEMATIALI',
 'SINFRA',
 'SINGROBO',
 'SIRASSO',
 'MOUSSAYO',
 'SOKORODOUGOU',
 'SOMINANSE',
 'SONDO',
 'SONGON',
 'SONGON DAGBE',
 'SONONZO',
 'SOROBANGO',
 'SOUBRE',
 'BALEYO',
 'ZUENOULA',
 'TAABO',
 'TABAGNE',
 'TABOU',
 'TAFIRE',
 'TAHIRAGUHE',
 'TAHOGORA',
 'TAI',
 'TALA',
 'TANDI',
 'TANDA',
 'TANGUELAN',
 'TANKESSE',
 'TAOUDI',
 'TINDENE BAMBARASSO',
 'TENGRELA',
 'TIAPOUM',
 'TIASSALE',
 'TIEBISSOU',
 'TIEMA',
 'TIEMELEKRO',
 'TIEME',
 'TIENDEKRO',
 'TIENKO',
 'TIMBE',
 'TIOBLY',
 'TOROGUHE',
 'TORO-KINKENE',
 'TORTYA',
 'TOUBA',
 'TOUKOUZOU',
 'TOULEUPLEU',
 'TOUMODI',
 'DJEKANOU',
 'TOUMODISAKASSOU',
 'TOUPAH',
 'TOUVRE',
 'TRANSUA',
 'VAVOUA',
 'VROUHO',
 'WENDENE',
 'WOROFLA',
 'YABAYO',
 'YAKASSE-ATTOBROU',
 'YAKASSEFEYASSE',
 'YAKASSEME',
 'YAOKRO',
 'YAOSEDOUGOU',
 'YAOU',
 'YOROBODI',
 'YOUWASSO',
 'ZAALA',
 'ZADDI',
 'ZAGNE',
 'ZAIBO',
 'ZALIOHOUAN',
 'ZAMBAKRO',
 'ZARANOU',
 'ZAROKO',
 'ZATTA',
 'ZIKISSO',
 'ZON-HOUNIEN',
 'ZOUKOUGBEU']

In [39]:
#loading data our CDR discription dataset for TELECOME DATASETS
df = pd.read_excel('CDR_description.xlsx')
df

       Column name                                        Description   Format
0          PRODUCT                                       Voice or SMS   String
1            VALUE                                      Billing price  Integer
2        DATE_TIME               Time in format yyyy-MM-dd hh:mm:ss.0   String
3     CELL_ON_SITE  Which cell in the site was used (not needed here)  Integer
4  DW_A_NUMBER_INT  Anonymized phone number of the person for whic...   String
5  DW_B_NUMBER_INT        Anonymized phone number of the counterparty   String
6        COUNTRY_A                  Country of party A (useless here)   String
7        COUNTRY_B                  Country of party B (useless here)   String
8          CELL_ID                                     ID of the cell   String
9          SITE_ID                                     ID of the SITE   String

In [104]:

#loading and creating Dataframe from Telecome dataset1 url=https://raw.githubusercontent.com/Ruthnguli/cells_geo/main/Telcom_dataset.csv

url = "https://raw.githubusercontent.com/Ruthnguli/cells_geo/main/Telcom_dataset.csv"
df_1 = pd.read_csv(url)
#viewing the first 10 rows
df_1.head(100)

,PRODUTC,VALUE,DATETIME,CELL_ON_SITE,DW_A_NUMBER_INT,DW_B_NUMBER_INT,COUNTRY_A,COUNTRY_B,CELL_ID,SITE_ID
0,Voice,0,2012-05-06 23:04:37.0,1,49fae048b547780,1a49f8b0ded9de6,19e2e,19e2e,/TJNe+Mmtu,/TJNe+Mmtu
1,sms,0,2012-05-06 23:05:25.0,0,7a54a6eaee19e65,93343ba6e41af95,19e2e,19e2e,/+cKZKIp41,/+cKZKIp41
2,sms,25,2012-05-06 23:05:41.0,0,6008887b0207d82,7aacc9709ce0a20,19e2e,19e2e,/u0FSD+ahi,/u0FSD+ahi
3,Voice,56,2012-05-06 23:05:42.0,1,7370032e20f4e96,6af4a60e74c91d3,19e2e,19e2e,+cNeJzsTp3,+cNeJzsTp3
4,Voice,14,2012-05-06 23:06:29.0,1,966ba4656e38e62,02aa736ee555d5c,19e2e,19e2e,051KhYDCpv,051KhYDCpv
5,data,0,2012-05-06 23:07:26.0,_,f71825ca6e623f9,5a4dc9e82deb309,19e2e,OTHER,/lrUXVGVcN,/lrUXVGVcN
6,Voice,0,2012-05-06 23:08:02.0,1,4afd7d5af21b1ce,67bf1ac30e58e2f,19e2e,19e2e,+38u2u/rfx,+38u2u/rfx
7,Voice,0,2012-05-06 23:08:03.0,5,d717dee81c51389,adde5afd9a67b10,19e2e,19e2e,09UjmmY1Ds,09UjmmY1Ds
8,Voice,0,2012-05-06 23:08:05.0,1,44522aefdc918a6,19e68e80103885e,19e2e,19e2e,0DeimCpZOc,0DeimCpZOc
9,sms,0,2012-05-06 23:08:43.0,0,0763a571d24db64,f773694c00c74d2,19e2e,19e2e,01MDiY5F89,01MDiY5F89
10,sms,0,2012-05-06 23:08:50.0,2,93105314189e879,d79384629278326,19e2e,19e2e,0Fmr/IZtQ+,0Fmr/IZtQ+
11,sms,0,2012-05-06 23:09:12.0,2,a53686548a74582,d164ed0a0cf2360,19e2e,19e2e,0MZBLLzPYZ,0MZBLLzPYZ
12,sms,0,2012-05-06 23:09:13.0,1,9938d2d3c72399e,ff0c464449d36fb,19e2e,19e2e,0//cZOoEXj,0//cZOoEXj
13,sms,25,2012-05-06 23:09:16.0,1,225a414d7f66444,4ee1446e20cbc0b,19e2e,19e2e,2dmu2Iy1CX,2dmu2Iy1CX
14,Voice,0,2012-05-06 23:09:26.0,1,d5b3ec1778ad8c0,cc36f4260f66fee,19e2e,19e2e,0Fmr/IZtQ+,0Fmr/IZtQ+
15,Voice,0,2012-05-06 23:09:51.0,0,c34ef4252d76415,73e1048bfe78617,19e2e,19e2e,176sGHv7Ym,176sGHv7Ym
16,Voice,44,2012-05-06 23:09:54.0,2,e708c33795563f1,8f9487c2e6f468e,19e2e,19e2e,++ctND+jGD,++ctND+jGD
17,Voice,0,2012-05-06 23:09:59.0,2,00dcbcd23dc675c,23a453f5189cc79,19e2e,19e2e,1JODMow6DN,1JODMow6DN
18,sms,0,2012-05-06 23:10:05.0,0,8ab8b9ed6989f61,e09e736e46c5c3d,19e2e,19e2e,2PbwFG2K9y,2PbwFG2K9y
19,Voice,14,2012-05-06 23:10:23.0,1,dad978f7b8a9a09,28a6bcdc24a8b38,19e2e,19e2e,2GgIN622rt,2GgIN622rt
20,data,0,2012-05-06 23:10:30.0,_,057c5fb59d8f14f,5a4dc9e82deb309,19e2e,OTHER,/vLAMOS+Qm,/vLAMOS+Qm
21,sms,0,2012-05-06 23:10:41.0,1,c5a7d9300397229,55742f0b8e5b08d,19e2e,19e2e,2dmu2Iy1CX,2dmu2Iy1CX
22,sms,50,2012-05-06 23:11:14.0,1,8ac7935e68f6ab3,a9e781764b4728a,19e2e,19e2e,2FzOAUm82C,2FzOAUm82C
23,data,0,2012-05-06 23:11:27.0,_,795c2a90bd8d442,5a4dc9e82deb309,19e2e,OTHER,2yuhUrSXQu,2yuhUrSXQu
24,Voice,0,2012-05-06 23:11:27.0,1,1a2b54695968d46,55ad144fa74fddc,19e2e,19e2e,3mQAiRAfo7,3mQAiRAfo7
25,data,0,2012-05-06 23:12:07.0,_,0471428956c85d0,5a4dc9e82deb309,19e2e,OTHER,2FzOAUm82C,2FzOAUm82C
26,Voice,0,2012-05-06 23:12:10.0,2,12c6cf3d45dc493,8f6917492bd38a0,19e2e,19e2e,+gySf02tKW,+gySf02tKW
27,Voice,19,2012-05-06 23:12:25.0,0,b0ffeee6fe3c759,3f830c98519c5e9,19e2e,19e2e,/EkqCbWDau,/EkqCbWDau
28,sms,25,2012-05-06 23:12:25.0,0,21939efec26bf4e,ba7e17ea91737fa,19e2e,19e2e,/kxqxDGV0Z,/kxqxDGV0Z
29,sms,0,2012-05-06 23:12:36.0,2,1e9789aacb2b6dd,93343ba6e41af95,19e2e,19e2e,4K++Px614U,4K++Px614U
30,Voice,192,2012-05-06 23:12:43.0,1,03dd5e41773fcf1,baef1e51b1c085e,19e2e,19e2e,1AX75JmPtt,1AX75JmPtt
31,sms,0,2012-05-06 23:12:45.0,1,68ec294ea33925a,35d1617eb07cfbd,19e2e,19e2e,0nabagle1r,0nabagle1r
32,Voice,99,2012-05-06 23:13:03.0,2,b3944e04b20094c,3f1bbb086396478,19e2e,19e2e,/u0FSD+ahi,/u0FSD+ahi
33,data,0,2012-05-06 23:13:05.0,_,0fd250fbfa13e35,5a4dc9e82deb309,19e2e,OTHER,+pZNtCvhmT,+pZNtCvhmT
34,sms,0,2012-05-06 23:13:09.0,1,9fd3fa5a17daf4b,961e7b6cbac744d,19e2e,19e2e,0MZBLLzPYZ,0MZBLLzPYZ
35,Voice,0,2012-05-06 23:13:13.0,2,252aa99ab878f94,19e68e80103885e,19e2e,19e2e,/kxqxDGV0Z,/kxqxDGV0Z
36,Voice,12,2012-05-06 23:13:23.0,5,83b900a619f705e,ee36bac8c42e2a0,19e2e,19e2e,4506CmswTv,4506CmswTv
37,Voice,0,2012-05-06 23:13:30.0,1,7eed97ed1f49805,04fcb7a2ddfa114,19e2e,19e2e,/+cKZKIp41,/+cKZKIp41
38,Voice,24,2012-05-06 23:13:41.0,2,f18d8c4d2650b28,f191d414e19b647,19e2e,19e2e,/vLAMOS+Qm,/vLAMOS+Qm
39,Voice,0,2012-05-06 23:13:45.0,2,493d46f989df544,19e68e80103885e,19e2e,19e2e,0nabagle1r,0nabagle1r
40,data,0,2012-05-06 23:13:59.0,_,ca7e0aacd143f2c,5a4dc9e82deb309,19e2e,OTHER,1DLa1Gsiik,1DLa1Gsiik
41,Voice,1610,2012-05-06 23:14:03.0,1,b2b3dbfe5ce4bc1,5bd824717c81913,19e2e,19e2e,47yB6si0R9,47yB6si0R9
42,Voice,0,2012-05-06 23:14:08.0,0,36ce4d9e29bfdbb,627f696d781c521,19e2e,19e2e,0K+IDi1yjl,0K+IDi1yjl
43,data,0,2012-05-06 23:14:20.0,_,9c91f5f17d98d25,5a4dc9e82deb309,19e2e,OTHER,051KhYDCpv,051KhYDCpv
44,sms,0,2012-05-06 23:14:40.0,1,d6dec69142f5f5a,679f88c531065ba,19e2e,19e2e,0eNnL1pokg,0eNnL1pokg
45,data,0,2012-05-06 23:15:04.0,_,ae42b2028567b5d,5a4dc9e82deb309,19e2e,OTHER,+laSrk7g6q,+laSrk7g6q
46,data,0,2012-05-06 23:15:04.0,_,a45bebd9e2b19a5,5a4dc9e82deb309,19e2e,OTHER,/eeMklgyJA,/eeMklgyJA
47,data,0,2012-05-06 23:15:09.0,_,cb8f0c91086fadd,5a4dc9e82deb309,19e2e,OTHER,+gQ2AvXjaO,+gQ2AvXjaO
48,Voice,14,2012-05-06 23:15:34.0,1,93f049b70a6385e,3999882b87379e2,19e2e,19e2e,35gi1DzgNK,35gi1DzgNK
49,Voice,152,2012-05-06 23:15:41.0,1,181fd413bd05a41,efdd10a06033e4a,19e2e,19e2e,54Pb8dz/52,54Pb8dz/52
50,Voice,138,2012-05-06 23:15:44.0,3,a7bdf6a50f8f847,66883e332453e1a,19e2e,19e2e,+38u2u/rfx,+38u2u/rfx
51,sms,0,2012-05-06 23:15:44.0,1,604372755943531,06817148de3ca32,19e2e,19e2e,+pZNtCvhmT,+pZNtCvhmT
52,Voice,30,2012-05-06 23:15:46.0,2,cc4f76d42d5a21f,2d6397576ae9152,19e2e,19e2e,1AX75JmPtt,1AX75JmPtt
53,sms,0,2012-05-06 23:15:48.0,0,afd684b4cffdee7,319a2143a4191d9,19e2e,19e2e,5RMks2Nhbt,5RMks2Nhbt
54,sms,0,2012-05-06 23:15:58.0,1,92d0003b1405a09,a167135c140a545,19e2e,OTHER,5RMks2Nhbt,5RMks2Nhbt
55,sms,0,2012-05-06 23:16:00.0,1,ecc5a1a16d86e83,0b02b98799ce11f,19e2e,19e2e,5bFHC1hRn8,5bFHC1hRn8
56,Voice,192,2012-05-06 23:16:02.0,2,daa196aae52640f,314143ad0d2f94b,19e2e,19e2e,0BRdojv2my,0BRdojv2my
57,sms,0,2012-05-06 23:16:05.0,2,4d4d215e2d934be,8f1eae9b235323f,19e2e,19e2e,+ZaaZozy/+,+ZaaZozy/+
58,Voice,0,2012-05-06 23:16:14.0,1,5adcd455399cdd8,ab5e1ede47a452e,19e2e,19e2e,2dmu2Iy1CX,2dmu2Iy1CX
59,Voice,0,2012-05-06 23:16:14.0,1,da76c9090f43e57,943a1edcb0b1241,19e2e,19e2e,51qrsXM+vt,51qrsXM+vt
60,Voice,0,2012-05-06 23:16:15.0,5,42fe0f47108cf94,ff17850074a3b9e,19e2e,19e2e,0MZBLLzPYZ,0MZBLLzPYZ
61,Voice,0,2012-05-06 23:16:42.0,1,6e3160f573cb5e7,cdcb1b47490a1eb,19e2e,19e2e,+gQ2AvXjaO,+gQ2AvXjaO
62,Voice,1,2012-05-06 23:16:52.0,2,e8990748d60e2b9,6a55cb848fb1f95,19e2e,19e2e,5lXcKLcxWE,5lXcKLcxWE
63,Voice,30,2012-05-06 23:16:54.0,4,6154eb39623c0fa,d1e1973bf3f5813,19e2e,19e2e,0DeimCpZOc,0DeimCpZOc
64,data,0,2012-05-06 23:17:02.0,_,e4e56cc9aef184a,5a4dc9e82deb309,19e2e,OTHER,3T/wsniMlZ,3T/wsniMlZ
65,Voice,2,2012-05-06 23:17:04.0,1,558120c4db30da4,2940e774bb5cc71,19e2e,19e2e,1mtIa2GRBc,1mtIa2GRBc
66,Voice,17,2012-05-06 23:17:07.0,1,380b266db76ef36,7d6200b049e82d9,19e2e,19e2e,/0LopuZdd7,/0LopuZdd7
67,sms,0,2012-05-06 23:17:09.0,1,b2709c518000035,1cb5baa42414c09,19e2e,19e2e,1JODMow6DN,1JODMow6DN
68,sms,0,2012-05-06 23:17:12.0,1,9938d2d3c72399e,15706a45bf23919,19e2e,19e2e,1DLa1Gsiik,1DLa1Gsiik
69,Voice,0,2012-05-06 23:17:15.0,2,6f19dbedcbc7adb,cb8f109b5c0db02,19e2e,19e2e,0MZBLLzPYZ,0MZBLLzPYZ
70,Voice,22,2012-05-06 23:17:26.0,1,6ef04af9aba7664,f0594085fa4dc29,19e2e,19e2e,6dZgOHeA29,6dZgOHeA29
71,data,20,2012-05-06 23:17:34.0,_,7a73858980301a4,5a4dc9e82deb309,19e2e,OTHER,+38u2u/rfx,+38u2u/rfx
72,Voice,21,2012-05-06 23:17:35.0,0,f106ca55f4a7d4d,16eb186c8eec862,19e2e,19e2e,3UXdSkM8V3,3UXdSkM8V3
73,Voice,21,2012-05-06 23:17:38.0,2,a59057f3ae5d93c,f48942a873250a9,19e2e,19e2e,60rBK3VnF7,60rBK3VnF7
74,Voice,27,2012-05-06 23:17:43.0,1,93e51bf562c41ed,1cbb833dfc260dc,19e2e,19e2e,4wcFwPWjZJ,4wcFwPWjZJ
75,sms,0,2012-05-06 23:17:58.0,1,0e80ff8bbb8a305,9a73be24b32e7f7,19e2e,19e2e,/eeMklgyJA,/eeMklgyJA
76,sms,0,2012-05-06 23:18:07.0,1,dcedf150f15b1d1,2268da7261a4954,19e2e,19e2e,18iJZATMMC,18iJZATMMC
77,Voice,16,2012-05-06 23:18:18.0,0,0f60d1525b456dd,e6eac19beeef28f,19e2e,19e2e,3u865XIo6c,3u865XIo6c
78,Voice,35,2012-05-06 23:18:24.0,0,3a78e2a3e1f554f,0c2dac3b4d8db53,19e2e,19e2e,3zwc9ry2i5,3zwc9ry2i5
79,sms,0,2012-05-06 23:18:35.0,4,9af3ad3c0ac209f,541c22fc455326b,19e2e,19e2e,2LuHm8D2MC,2LuHm8D2MC
80,sms,0,2012-05-06 23:18:41.0,0,fc29d09837d792a,aaaf0e4bdec7311,19e2e,19e2e,7ECXh+RvQZ,7ECXh+RvQZ
81,Voice,0,2012-05-06 23:18:47.0,5,745bbfd1f72cae8,dc241ca171f791d,19e2e,19e2e,4iv1FNJ67I,4iv1FNJ67I
82,Voice,201,2012-05-06 23:19:00.0,0,a49667cb69c38bf,27508193f23a09b,19e2e,19e2e,22Z3fM8uPX,22Z3fM8uPX
83,Voice,14,2012-05-06 23:19:04.0,1,113bfd52be7d647,f282d974e5d0b80,19e2e,19e2e,44o98M/wq3,44o98M/wq3
84,sms,0,2012-05-06 23:19:06.0,1,2097ee231e6607a,32433760a16d6a0,19e2e,19e2e,77XAFQmoad,77XAFQmoad
85,sms,0,2012-05-06 23:19:09.0,1,7c52cea484856d4,e4943767888b71e,19e2e,19e2e,35gi1DzgNK,35gi1DzgNK
86,Voice,0,2012-05-06 23:19:14.0,0,da45e1d1637ca27,00aa565e559b72c,19e2e,19e2e,01MDiY5F89,01MDiY5F89
87,Voice,74,2012-05-06 23:19:28.0,2,8d53d02164e224d,e8c3a722ce885d3,19e2e,19e2e,2cj/HbqLAV,2cj/HbqLAV
88,Voice,0,2012-05-06 23:19:30.0,5,22671dc72653a38,b22f97a97a5f14c,19e2e,19e2e,0/eYPFomxx,0/eYPFomxx
89,Voice,0,2012-05-06 23:19:30.0,4,31fd363604c4492,19e68e80103885e,19e2e,19e2e,3cVu6QQcZ6,3cVu6QQcZ6
90,Voice,0,2012-05-06 23:19:49.0,0,71b9974b00f24d2,fb3413b0c455588,19e2e,19e2e,2ygIBia4Re,2ygIBia4Re
91,sms,0,2012-05-06 23:19:59.0,2,cb6a02fde166b94,aaaf0e4bdec7311,19e2e,19e2e,+weksowKR7,+weksowKR7
92,sms,0,2012-05-06 23:20:28.0,1,03acafb19701ab5,e61ad60cd75d305,19e2e,19e2e,301gn/BrU5,301gn/BrU5
93,Voice,0,2012-05-06 23:20:47.0,4,a98edb163d40b7b,55ad144fa74fddc,19e2e,19e2e,+854AcBQT2,+854AcBQT2
94,Voice,31,2012-05-06 23:20:50.0,2,5f1885cff7736f9,628171e4aa59f04,19e2e,19e2e,4wcFwPWjZJ,4wcFwPWjZJ
95,sms,0,2012-05-06 23:21:20.0,0,2b3dd08f3b1bd5f,e09e736e46c5c3d,19e2e,19e2e,/MMplBlWjh,/MMplBlWjh
96,sms,0,2012-05-06 23:21:30.0,1,26bba173fb6c85a,2d4a359d7bc0c55,19e2e,19e2e,6KGV6b77hq,6KGV6b77hq
97,Voice,3,2012-05-06 23:21:31.0,1,57850d753b4fd91,99f718df6351c6e,19e2e,19e2e,8JgRZeFDVZ,8JgRZeFDVZ
98,Voice,38,2012-05-06 23:21:37.0,0,5c1e0cc5b8fd177,0903612915f5d06,19e2e,19e2e,2yuhUrSXQu,2yuhUrSXQu
99,data,0,2012-05-06 23:21:38.0,_,8dbee05f1afc0cf,5a4dc9e82deb309,19e2e,OTHER,2vqM21lFHK,2vqM21lFHK

In [105]:

#Update column PRODUTc and DATATIME to PRODUCT and DATA_TIME as per the description

df_1_new = (df_1.rename(columns={'PRODUTC': 'PRODUCT', 'DATETIME': 'DATE_TIME'}))
df_1_new.head(100)

,PRODUCT,VALUE,DATE_TIME,CELL_ON_SITE,DW_A_NUMBER_INT,DW_B_NUMBER_INT,COUNTRY_A,COUNTRY_B,CELL_ID,SITE_ID
0,Voice,0,2012-05-06 23:04:37.0,1,49fae048b547780,1a49f8b0ded9de6,19e2e,19e2e,/TJNe+Mmtu,/TJNe+Mmtu
1,sms,0,2012-05-06 23:05:25.0,0,7a54a6eaee19e65,93343ba6e41af95,19e2e,19e2e,/+cKZKIp41,/+cKZKIp41
2,sms,25,2012-05-06 23:05:41.0,0,6008887b0207d82,7aacc9709ce0a20,19e2e,19e2e,/u0FSD+ahi,/u0FSD+ahi
3,Voice,56,2012-05-06 23:05:42.0,1,7370032e20f4e96,6af4a60e74c91d3,19e2e,19e2e,+cNeJzsTp3,+cNeJzsTp3
4,Voice,14,2012-05-06 23:06:29.0,1,966ba4656e38e62,02aa736ee555d5c,19e2e,19e2e,051KhYDCpv,051KhYDCpv
5,data,0,2012-05-06 23:07:26.0,_,f71825ca6e623f9,5a4dc9e82deb309,19e2e,OTHER,/lrUXVGVcN,/lrUXVGVcN
6,Voice,0,2012-05-06 23:08:02.0,1,4afd7d5af21b1ce,67bf1ac30e58e2f,19e2e,19e2e,+38u2u/rfx,+38u2u/rfx
7,Voice,0,2012-05-06 23:08:03.0,5,d717dee81c51389,adde5afd9a67b10,19e2e,19e2e,09UjmmY1Ds,09UjmmY1Ds
8,Voice,0,2012-05-06 23:08:05.0,1,44522aefdc918a6,19e68e80103885e,19e2e,19e2e,0DeimCpZOc,0DeimCpZOc
9,sms,0,2012-05-06 23:08:43.0,0,0763a571d24db64,f773694c00c74d2,19e2e,19e2e,01MDiY5F89,01MDiY5F89
10,sms,0,2012-05-06 23:08:50.0,2,93105314189e879,d79384629278326,19e2e,19e2e,0Fmr/IZtQ+,0Fmr/IZtQ+
11,sms,0,2012-05-06 23:09:12.0,2,a53686548a74582,d164ed0a0cf2360,19e2e,19e2e,0MZBLLzPYZ,0MZBLLzPYZ
12,sms,0,2012-05-06 23:09:13.0,1,9938d2d3c72399e,ff0c464449d36fb,19e2e,19e2e,0//cZOoEXj,0//cZOoEXj
13,sms,25,2012-05-06 23:09:16.0,1,225a414d7f66444,4ee1446e20cbc0b,19e2e,19e2e,2dmu2Iy1CX,2dmu2Iy1CX
14,Voice,0,2012-05-06 23:09:26.0,1,d5b3ec1778ad8c0,cc36f4260f66fee,19e2e,19e2e,0Fmr/IZtQ+,0Fmr/IZtQ+
15,Voice,0,2012-05-06 23:09:51.0,0,c34ef4252d76415,73e1048bfe78617,19e2e,19e2e,176sGHv7Ym,176sGHv7Ym
16,Voice,44,2012-05-06 23:09:54.0,2,e708c33795563f1,8f9487c2e6f468e,19e2e,19e2e,++ctND+jGD,++ctND+jGD
17,Voice,0,2012-05-06 23:09:59.0,2,00dcbcd23dc675c,23a453f5189cc79,19e2e,19e2e,1JODMow6DN,1JODMow6DN
18,sms,0,2012-05-06 23:10:05.0,0,8ab8b9ed6989f61,e09e736e46c5c3d,19e2e,19e2e,2PbwFG2K9y,2PbwFG2K9y
19,Voice,14,2012-05-06 23:10:23.0,1,dad978f7b8a9a09,28a6bcdc24a8b38,19e2e,19e2e,2GgIN622rt,2GgIN622rt
20,data,0,2012-05-06 23:10:30.0,_,057c5fb59d8f14f,5a4dc9e82deb309,19e2e,OTHER,/vLAMOS+Qm,/vLAMOS+Qm
21,sms,0,2012-05-06 23:10:41.0,1,c5a7d9300397229,55742f0b8e5b08d,19e2e,19e2e,2dmu2Iy1CX,2dmu2Iy1CX
22,sms,50,2012-05-06 23:11:14.0,1,8ac7935e68f6ab3,a9e781764b4728a,19e2e,19e2e,2FzOAUm82C,2FzOAUm82C
23,data,0,2012-05-06 23:11:27.0,_,795c2a90bd8d442,5a4dc9e82deb309,19e2e,OTHER,2yuhUrSXQu,2yuhUrSXQu
24,Voice,0,2012-05-06 23:11:27.0,1,1a2b54695968d46,55ad144fa74fddc,19e2e,19e2e,3mQAiRAfo7,3mQAiRAfo7
25,data,0,2012-05-06 23:12:07.0,_,0471428956c85d0,5a4dc9e82deb309,19e2e,OTHER,2FzOAUm82C,2FzOAUm82C
26,Voice,0,2012-05-06 23:12:10.0,2,12c6cf3d45dc493,8f6917492bd38a0,19e2e,19e2e,+gySf02tKW,+gySf02tKW
27,Voice,19,2012-05-06 23:12:25.0,0,b0ffeee6fe3c759,3f830c98519c5e9,19e2e,19e2e,/EkqCbWDau,/EkqCbWDau
28,sms,25,2012-05-06 23:12:25.0,0,21939efec26bf4e,ba7e17ea91737fa,19e2e,19e2e,/kxqxDGV0Z,/kxqxDGV0Z
29,sms,0,2012-05-06 23:12:36.0,2,1e9789aacb2b6dd,93343ba6e41af95,19e2e,19e2e,4K++Px614U,4K++Px614U
30,Voice,192,2012-05-06 23:12:43.0,1,03dd5e41773fcf1,baef1e51b1c085e,19e2e,19e2e,1AX75JmPtt,1AX75JmPtt
31,sms,0,2012-05-06 23:12:45.0,1,68ec294ea33925a,35d1617eb07cfbd,19e2e,19e2e,0nabagle1r,0nabagle1r
32,Voice,99,2012-05-06 23:13:03.0,2,b3944e04b20094c,3f1bbb086396478,19e2e,19e2e,/u0FSD+ahi,/u0FSD+ahi
33,data,0,2012-05-06 23:13:05.0,_,0fd250fbfa13e35,5a4dc9e82deb309,19e2e,OTHER,+pZNtCvhmT,+pZNtCvhmT
34,sms,0,2012-05-06 23:13:09.0,1,9fd3fa5a17daf4b,961e7b6cbac744d,19e2e,19e2e,0MZBLLzPYZ,0MZBLLzPYZ
35,Voice,0,2012-05-06 23:13:13.0,2,252aa99ab878f94,19e68e80103885e,19e2e,19e2e,/kxqxDGV0Z,/kxqxDGV0Z
36,Voice,12,2012-05-06 23:13:23.0,5,83b900a619f705e,ee36bac8c42e2a0,19e2e,19e2e,4506CmswTv,4506CmswTv
37,Voice,0,2012-05-06 23:13:30.0,1,7eed97ed1f49805,04fcb7a2ddfa114,19e2e,19e2e,/+cKZKIp41,/+cKZKIp41
38,Voice,24,2012-05-06 23:13:41.0,2,f18d8c4d2650b28,f191d414e19b647,19e2e,19e2e,/vLAMOS+Qm,/vLAMOS+Qm
39,Voice,0,2012-05-06 23:13:45.0,2,493d46f989df544,19e68e80103885e,19e2e,19e2e,0nabagle1r,0nabagle1r
40,data,0,2012-05-06 23:13:59.0,_,ca7e0aacd143f2c,5a4dc9e82deb309,19e2e,OTHER,1DLa1Gsiik,1DLa1Gsiik
41,Voice,1610,2012-05-06 23:14:03.0,1,b2b3dbfe5ce4bc1,5bd824717c81913,19e2e,19e2e,47yB6si0R9,47yB6si0R9
42,Voice,0,2012-05-06 23:14:08.0,0,36ce4d9e29bfdbb,627f696d781c521,19e2e,19e2e,0K+IDi1yjl,0K+IDi1yjl
43,data,0,2012-05-06 23:14:20.0,_,9c91f5f17d98d25,5a4dc9e82deb309,19e2e,OTHER,051KhYDCpv,051KhYDCpv
44,sms,0,2012-05-06 23:14:40.0,1,d6dec69142f5f5a,679f88c531065ba,19e2e,19e2e,0eNnL1pokg,0eNnL1pokg
45,data,0,2012-05-06 23:15:04.0,_,ae42b2028567b5d,5a4dc9e82deb309,19e2e,OTHER,+laSrk7g6q,+laSrk7g6q
46,data,0,2012-05-06 23:15:04.0,_,a45bebd9e2b19a5,5a4dc9e82deb309,19e2e,OTHER,/eeMklgyJA,/eeMklgyJA
47,data,0,2012-05-06 23:15:09.0,_,cb8f0c91086fadd,5a4dc9e82deb309,19e2e,OTHER,+gQ2AvXjaO,+gQ2AvXjaO
48,Voice,14,2012-05-06 23:15:34.0,1,93f049b70a6385e,3999882b87379e2,19e2e,19e2e,35gi1DzgNK,35gi1DzgNK
49,Voice,152,2012-05-06 23:15:41.0,1,181fd413bd05a41,efdd10a06033e4a,19e2e,19e2e,54Pb8dz/52,54Pb8dz/52
50,Voice,138,2012-05-06 23:15:44.0,3,a7bdf6a50f8f847,66883e332453e1a,19e2e,19e2e,+38u2u/rfx,+38u2u/rfx
51,sms,0,2012-05-06 23:15:44.0,1,604372755943531,06817148de3ca32,19e2e,19e2e,+pZNtCvhmT,+pZNtCvhmT
52,Voice,30,2012-05-06 23:15:46.0,2,cc4f76d42d5a21f,2d6397576ae9152,19e2e,19e2e,1AX75JmPtt,1AX75JmPtt
53,sms,0,2012-05-06 23:15:48.0,0,afd684b4cffdee7,319a2143a4191d9,19e2e,19e2e,5RMks2Nhbt,5RMks2Nhbt
54,sms,0,2012-05-06 23:15:58.0,1,92d0003b1405a09,a167135c140a545,19e2e,OTHER,5RMks2Nhbt,5RMks2Nhbt
55,sms,0,2012-05-06 23:16:00.0,1,ecc5a1a16d86e83,0b02b98799ce11f,19e2e,19e2e,5bFHC1hRn8,5bFHC1hRn8
56,Voice,192,2012-05-06 23:16:02.0,2,daa196aae52640f,314143ad0d2f94b,19e2e,19e2e,0BRdojv2my,0BRdojv2my
57,sms,0,2012-05-06 23:16:05.0,2,4d4d215e2d934be,8f1eae9b235323f,19e2e,19e2e,+ZaaZozy/+,+ZaaZozy/+
58,Voice,0,2012-05-06 23:16:14.0,1,5adcd455399cdd8,ab5e1ede47a452e,19e2e,19e2e,2dmu2Iy1CX,2dmu2Iy1CX
59,Voice,0,2012-05-06 23:16:14.0,1,da76c9090f43e57,943a1edcb0b1241,19e2e,19e2e,51qrsXM+vt,51qrsXM+vt
60,Voice,0,2012-05-06 23:16:15.0,5,42fe0f47108cf94,ff17850074a3b9e,19e2e,19e2e,0MZBLLzPYZ,0MZBLLzPYZ
61,Voice,0,2012-05-06 23:16:42.0,1,6e3160f573cb5e7,cdcb1b47490a1eb,19e2e,19e2e,+gQ2AvXjaO,+gQ2AvXjaO
62,Voice,1,2012-05-06 23:16:52.0,2,e8990748d60e2b9,6a55cb848fb1f95,19e2e,19e2e,5lXcKLcxWE,5lXcKLcxWE
63,Voice,30,2012-05-06 23:16:54.0,4,6154eb39623c0fa,d1e1973bf3f5813,19e2e,19e2e,0DeimCpZOc,0DeimCpZOc
64,data,0,2012-05-06 23:17:02.0,_,e4e56cc9aef184a,5a4dc9e82deb309,19e2e,OTHER,3T/wsniMlZ,3T/wsniMlZ
65,Voice,2,2012-05-06 23:17:04.0,1,558120c4db30da4,2940e774bb5cc71,19e2e,19e2e,1mtIa2GRBc,1mtIa2GRBc
66,Voice,17,2012-05-06 23:17:07.0,1,380b266db76ef36,7d6200b049e82d9,19e2e,19e2e,/0LopuZdd7,/0LopuZdd7
67,sms,0,2012-05-06 23:17:09.0,1,b2709c518000035,1cb5baa42414c09,19e2e,19e2e,1JODMow6DN,1JODMow6DN
68,sms,0,2012-05-06 23:17:12.0,1,9938d2d3c72399e,15706a45bf23919,19e2e,19e2e,1DLa1Gsiik,1DLa1Gsiik
69,Voice,0,2012-05-06 23:17:15.0,2,6f19dbedcbc7adb,cb8f109b5c0db02,19e2e,19e2e,0MZBLLzPYZ,0MZBLLzPYZ
70,Voice,22,2012-05-06 23:17:26.0,1,6ef04af9aba7664,f0594085fa4dc29,19e2e,19e2e,6dZgOHeA29,6dZgOHeA29
71,data,20,2012-05-06 23:17:34.0,_,7a73858980301a4,5a4dc9e82deb309,19e2e,OTHER,+38u2u/rfx,+38u2u/rfx
72,Voice,21,2012-05-06 23:17:35.0,0,f106ca55f4a7d4d,16eb186c8eec862,19e2e,19e2e,3UXdSkM8V3,3UXdSkM8V3
73,Voice,21,2012-05-06 23:17:38.0,2,a59057f3ae5d93c,f48942a873250a9,19e2e,19e2e,60rBK3VnF7,60rBK3VnF7
74,Voice,27,2012-05-06 23:17:43.0,1,93e51bf562c41ed,1cbb833dfc260dc,19e2e,19e2e,4wcFwPWjZJ,4wcFwPWjZJ
75,sms,0,2012-05-06 23:17:58.0,1,0e80ff8bbb8a305,9a73be24b32e7f7,19e2e,19e2e,/eeMklgyJA,/eeMklgyJA
76,sms,0,2012-05-06 23:18:07.0,1,dcedf150f15b1d1,2268da7261a4954,19e2e,19e2e,18iJZATMMC,18iJZATMMC
77,Voice,16,2012-05-06 23:18:18.0,0,0f60d1525b456dd,e6eac19beeef28f,19e2e,19e2e,3u865XIo6c,3u865XIo6c
78,Voice,35,2012-05-06 23:18:24.0,0,3a78e2a3e1f554f,0c2dac3b4d8db53,19e2e,19e2e,3zwc9ry2i5,3zwc9ry2i5
79,sms,0,2012-05-06 23:18:35.0,4,9af3ad3c0ac209f,541c22fc455326b,19e2e,19e2e,2LuHm8D2MC,2LuHm8D2MC
80,sms,0,2012-05-06 23:18:41.0,0,fc29d09837d792a,aaaf0e4bdec7311,19e2e,19e2e,7ECXh+RvQZ,7ECXh+RvQZ
81,Voice,0,2012-05-06 23:18:47.0,5,745bbfd1f72cae8,dc241ca171f791d,19e2e,19e2e,4iv1FNJ67I,4iv1FNJ67I
82,Voice,201,2012-05-06 23:19:00.0,0,a49667cb69c38bf,27508193f23a09b,19e2e,19e2e,22Z3fM8uPX,22Z3fM8uPX
83,Voice,14,2012-05-06 23:19:04.0,1,113bfd52be7d647,f282d974e5d0b80,19e2e,19e2e,44o98M/wq3,44o98M/wq3
84,sms,0,2012-05-06 23:19:06.0,1,2097ee231e6607a,32433760a16d6a0,19e2e,19e2e,77XAFQmoad,77XAFQmoad
85,sms,0,2012-05-06 23:19:09.0,1,7c52cea484856d4,e4943767888b71e,19e2e,19e2e,35gi1DzgNK,35gi1DzgNK
86,Voice,0,2012-05-06 23:19:14.0,0,da45e1d1637ca27,00aa565e559b72c,19e2e,19e2e,01MDiY5F89,01MDiY5F89
87,Voice,74,2012-05-06 23:19:28.0,2,8d53d02164e224d,e8c3a722ce885d3,19e2e,19e2e,2cj/HbqLAV,2cj/HbqLAV
88,Voice,0,2012-05-06 23:19:30.0,5,22671dc72653a38,b22f97a97a5f14c,19e2e,19e2e,0/eYPFomxx,0/eYPFomxx
89,Voice,0,2012-05-06 23:19:30.0,4,31fd363604c4492,19e68e80103885e,19e2e,19e2e,3cVu6QQcZ6,3cVu6QQcZ6
90,Voice,0,2012-05-06 23:19:49.0,0,71b9974b00f24d2,fb3413b0c455588,19e2e,19e2e,2ygIBia4Re,2ygIBia4Re
91,sms,0,2012-05-06 23:19:59.0,2,cb6a02fde166b94,aaaf0e4bdec7311,19e2e,19e2e,+weksowKR7,+weksowKR7
92,sms,0,2012-05-06 23:20:28.0,1,03acafb19701ab5,e61ad60cd75d305,19e2e,19e2e,301gn/BrU5,301gn/BrU5
93,Voice,0,2012-05-06 23:20:47.0,4,a98edb163d40b7b,55ad144fa74fddc,19e2e,19e2e,+854AcBQT2,+854AcBQT2
94,Voice,31,2012-05-06 23:20:50.0,2,5f1885cff7736f9,628171e4aa59f04,19e2e,19e2e,4wcFwPWjZJ,4wcFwPWjZJ
95,sms,0,2012-05-06 23:21:20.0,0,2b3dd08f3b1bd5f,e09e736e46c5c3d,19e2e,19e2e,/MMplBlWjh,/MMplBlWjh
96,sms,0,2012-05-06 23:21:30.0,1,26bba173fb6c85a,2d4a359d7bc0c55,19e2e,19e2e,6KGV6b77hq,6KGV6b77hq
97,Voice,3,2012-05-06 23:21:31.0,1,57850d753b4fd91,99f718df6351c6e,19e2e,19e2e,8JgRZeFDVZ,8JgRZeFDVZ
98,Voice,38,2012-05-06 23:21:37.0,0,5c1e0cc5b8fd177,0903612915f5d06,19e2e,19e2e,2yuhUrSXQu,2yuhUrSXQu
99,data,0,2012-05-06 23:21:38.0,_,8dbee05f1afc0cf,5a4dc9e82deb309,19e2e,OTHER,2vqM21lFHK,2vqM21lFHK

In [51]:
# #loading and creating Dataframe from Telecome dataset2 url =https://raw.githubusercontent.com/Ruthnguli/cells_geo/main/Telcom_dataset2.csv
url = "https://raw.githubusercontent.com/Ruthnguli/cells_geo/main/Telcom_dataset2.csv"
df_2 = pd.read_csv(url)
#viewing the first 10 rows
df_2.head(10)

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0     sms      0  2012-05-07 23:02:06.0  ...     19e2e  +854AcBQT2  +854AcBQT2
1   Voice      0  2012-05-07 23:03:44.0  ...     19e2e  +854AcBQT2  +854AcBQT2
2     sms      0  2012-05-07 23:04:06.0  ...     19e2e  +laSrk7g6q  +laSrk7g6q
3   Voice     37  2012-05-07 23:04:48.0  ...     19e2e  /xvRrCVKoQ  /xvRrCVKoQ
4     sms     25  2012-05-07 23:04:58.0  ...     19e2e  +bO+qkSonO  +bO+qkSonO
5     sms      0  2012-05-07 23:05:41.0  ...     19e2e  /MMplBlWjh  /MMplBlWjh
6   Voice     41  2012-05-07 23:06:14.0  ...     19e2e  +laSrk7g6q  +laSrk7g6q
7   Voice     11  2012-05-07 23:06:28.0  ...     19e2e  +gySf02tKW  +gySf02tKW
8     sms      0  2012-05-07 23:06:35.0  ...     OTHER  /0FxP3az1x  /0FxP3az1x
9     sms      0  2012-05-07 23:06:50.0  ...     19e2e  0ecjmwPX21  0ecjmwPX21

[10 rows x 10 columns]

In [73]:
#updating columns DW_A_NUMBER and 	DW_B_NUMBER	to DW_A_NUMBER_INT	DW_B_NUMBER_INT to march the description
df_2_new = (df_2.rename(columns={'DW_A_NUMBER': 'DW_A_NUMBER_INT', 'DW_B_NUMBER': 'DW_B_NUMBER_INT'}))
df_2_new

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0        sms      0  2012-05-07 23:02:06.0  ...     19e2e  +854AcBQT2  +854AcBQT2
1      Voice      0  2012-05-07 23:03:44.0  ...     19e2e  +854AcBQT2  +854AcBQT2
2        sms      0  2012-05-07 23:04:06.0  ...     19e2e  +laSrk7g6q  +laSrk7g6q
3      Voice     37  2012-05-07 23:04:48.0  ...     19e2e  /xvRrCVKoQ  /xvRrCVKoQ
4        sms     25  2012-05-07 23:04:58.0  ...     19e2e  +bO+qkSonO  +bO+qkSonO
...      ...    ...                    ...  ...       ...         ...         ...
4996     sms      0  2012-05-08 00:01:53.0  ...     19e2e  896459aace  b7d00e59e4
4997     sms     25  2012-05-08 00:01:53.0  ...     19e2e  7e90b35166  211015b14d
4998     sms      0  2012-05-08 00:01:53.0  ...     19e2e  fe70e431df  c7ea989264
4999    data      0  2012-05-08 00:01:53.0  ...     OTHER  ffa6759bb2         NaN
5000   Voice      0  2012-05-08 00:01:53.0  ...     19e2e  8630058aca  b47a998a3e

[5001 rows x 10 columns]

In [60]:

# loading and creating Dataframe from Telecome dataset3 url = https://raw.githubusercontent.com/Ruthnguli/cells_geo/main/Telcom_dataset3.csv

url = "https://raw.githubusercontent.com/Ruthnguli/cells_geo/main/Telcom_dataset3.csv"

df_3 = pd.read_csv(url)
#viewing the first 10 rows
df_3.head(10)

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B      CELLID     SIET_ID
0   Voice     61  2012-05-08 23:01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1     sms      0  2012-05-08 23:01:31.0  ...     19e2e  +Fs4mTvdKx  +Fs4mTvdKx
2   Voice     10  2012-05-08 23:02:59.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
3     sms      0  2012-05-08 23:03:04.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4   Voice     22  2012-05-08 23:03:16.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA
5   Voice     10  2012-05-08 23:03:59.0  ...     19e2e  +e+xcimwre  +e+xcimwre
6     sms      0  2012-05-08 23:06:06.0  ...     19e2e  +R5ccmtyJf  +R5ccmtyJf
7   Voice     10  2012-05-08 23:06:55.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
8     sms     25  2012-05-08 23:07:09.0  ...     19e2e  13O1+JEun3  13O1+JEun3
9     sms      0  2012-05-08 23:07:38.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA

[10 rows x 10 columns]

In [74]:
#updating columns CELLID and SIET_ID to CELL_ID and SITE_ID to march the description
df_3_new = (df_3.rename(columns={'CELLID': 'CELL_ID', 'SIET_ID': 'SITE_ID'}))
df_3_new

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0      Voice     61  2012-05-08 23:01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1        sms      0  2012-05-08 23:01:31.0  ...     19e2e  +Fs4mTvdKx  +Fs4mTvdKx
2      Voice     10  2012-05-08 23:02:59.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
3        sms      0  2012-05-08 23:03:04.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4      Voice     22  2012-05-08 23:03:16.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA
...      ...    ...                    ...  ...       ...         ...         ...
4996   Voice      0  2012-05-09 00:01:43.0  ...     19e2e  2aa04dcab7  f7d63a29e5
4997   Voice     62  2012-05-09 00:01:43.0  ...     19e2e  7f1f2f889f  b4ddb9e93c
4998   Voice     32  2012-05-09 00:01:43.0  ...     19e2e  a4731e780e  d68260ef50
4999   Voice     30  2012-05-09 00:01:43.0  ...     19e2e  98ed726da2  b4130b54ab
5000   Voice     60  2012-05-09 00:01:43.0  ...     19e2e  1c11a2fcbb  6d70dae094

[5001 rows x 10 columns]

In [68]:
#merge the 3 CDR TELECOM DATAFRAMES

CDR_TELECOM = pd.concat([df_1_new, df_2_new,df_3_new], axis=0)
CDR_TELECOM

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0      Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1        sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2        sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3      Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4      Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
...      ...    ...                    ...  ...       ...         ...         ...
4996   Voice      0  2012-05-09 00:01:43.0  ...     19e2e  2aa04dcab7  f7d63a29e5
4997   Voice     62  2012-05-09 00:01:43.0  ...     19e2e  7f1f2f889f  b4ddb9e93c
4998   Voice     32  2012-05-09 00:01:43.0  ...     19e2e  a4731e780e  d68260ef50
4999   Voice     30  2012-05-09 00:01:43.0  ...     19e2e  98ed726da2  b4130b54ab
5000   Voice     60  2012-05-09 00:01:43.0  ...     19e2e  1c11a2fcbb  6d70dae094

[15003 rows x 10 columns]

In [90]:
#Merging the new marged Dataset CDR DATAFRAME with the cell geo dataframe


dfm = CDR_TELECOM.merge(df_new, how='left', on='SITE_ID')
dfm

      PRODUCT  VALUE              DATE_TIME  ...  REGION           AREA   CELL_ID_y
0       Voice      0  2012-05-06 23:04:37.0  ...     NaN            NaN         NaN
1         sms      0  2012-05-06 23:05:25.0  ...     NaN            NaN         NaN
2         sms     25  2012-05-06 23:05:41.0  ...     NaN            NaN         NaN
3       Voice     56  2012-05-06 23:05:42.0  ...     NaN            NaN         NaN
4       Voice     14  2012-05-06 23:06:29.0  ...     NaN            NaN         NaN
...       ...    ...                    ...  ...     ...            ...         ...
55911   Voice     60  2012-05-09 00:01:43.0  ...  LAGUNE  ABIDJAN NORTH  ed1b508bc9
55912   Voice     60  2012-05-09 00:01:43.0  ...  LAGUNE  ABIDJAN NORTH  3795ad5cbd
55913   Voice     60  2012-05-09 00:01:43.0  ...  LAGUNE  ABIDJAN NORTH  09a60b0991
55914   Voice     60  2012-05-09 00:01:43.0  ...  LAGUNE  ABIDJAN NORTH  a1b0a4671d
55915   Voice     60  2012-05-09 00:01:43.0  ...  LAGUNE  ABIDJAN NORTH  979062ae01

[55916 rows x 21 columns]

In [127]:
# Data cleaning
#Identify and drop duplicate rows

dfdup = dfm.duplicated()
dfdup

0        False
1        False
2        False
3        False
4        False
         ...
55911    False
55912    False
55913    False
55914    False
55915    False
Length: 55916, dtype: bool

In [128]:
#Droping the duplicated rows

dfnew = dfm.drop_duplicates()
dfnew

,PRODUCT,VALUE,DATE_TIME,CELL_ON_SITE,DW_A_NUMBER_INT,DW_B_NUMBER_INT,COUNTRY_A,COUNTRY_B,CELL_ID_x,SITE_ID,Unnamed: 0,CITY,STATUS,LOCALISATION,DECOUPZONE,ZONENAME,LONGITUDE,LATITUDE,REGION,AREA,CELL_ID_y
0,Voice,0,2012-05-06 23:04:37.0,1,49fae048b547780,1a49f8b0ded9de6,19e2e,19e2e,/TJNe+Mmtu,/TJNe+Mmtu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sms,0,2012-05-06 23:05:25.0,0,7a54a6eaee19e65,93343ba6e41af95,19e2e,19e2e,/+cKZKIp41,/+cKZKIp41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sms,25,2012-05-06 23:05:41.0,0,6008887b0207d82,7aacc9709ce0a20,19e2e,19e2e,/u0FSD+ahi,/u0FSD+ahi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Voice,56,2012-05-06 23:05:42.0,1,7370032e20f4e96,6af4a60e74c91d3,19e2e,19e2e,+cNeJzsTp3,+cNeJzsTp3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Voice,14,2012-05-06 23:06:29.0,1,966ba4656e38e62,02aa736ee555d5c,19e2e,19e2e,051KhYDCpv,051KhYDCpv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55911,Voice,60,2012-05-09 00:01:43.0,2,6edeb4c55714650,7e60838216482a7,19e2e,19e2e,1c11a2fcbb,6d70dae094,1110.0,ATTECOUBE,In Service,ABIDJAN,Abidjan_OUEST,ZONE C - Abidjan_OUEST,-4.0355,5.357528,LAGUNE,ABIDJAN NORTH,ed1b508bc9
55912,Voice,60,2012-05-09 00:01:43.0,2,6edeb4c55714650,7e60838216482a7,19e2e,19e2e,1c11a2fcbb,6d70dae094,1111.0,ATTECOUBE,In Service,ABIDJAN,Abidjan_OUEST,ZONE C - Abidjan_OUEST,-4.0355,5.357528,LAGUNE,ABIDJAN NORTH,3795ad5cbd
55913,Voice,60,2012-05-09 00:01:43.0,2,6edeb4c55714650,7e60838216482a7,19e2e,19e2e,1c11a2fcbb,6d70dae094,1112.0,ATTECOUBE,In Service,ABIDJAN,Abidjan_OUEST,ZONE C - Abidjan_OUEST,-4.0355,5.357528,LAGUNE,ABIDJAN NORTH,09a60b0991
55914,Voice,60,2012-05-09 00:01:43.0,2,6edeb4c55714650,7e60838216482a7,19e2e,19e2e,1c11a2fcbb,6d70dae094,1113.0,ATTECOUBE,In Service,ABIDJAN,Abidjan_OUEST,ZONE C - Abidjan_OUEST,-4.0355,5.357528,LAGUNE,ABIDJAN NORTH,a1b0a4671d
55915,Voice,60,2012-05-09 00:01:43.0,2,6edeb4c55714650,7e60838216482a7,19e2e,19e2e,1c11a2fcbb,6d70dae094,1114.0,ATTECOUBE,In Service,ABIDJAN,Abidjan_OUEST,ZONE C - Abidjan_OUEST,-4.0355,5.357528,LAGUNE,ABIDJAN NORTH,979062ae01

In [163]:
#DATA ANALYSIS

#Most used city for the three days
count = dfnew['CITY'].value_counts()
count.head (10)


#the most used city was YOPOUGON adn the list was DANANON

YOPOUGON        8549
ABOBO           6159
COCODY          3716
ADJAME          2655
KOUMASSI        2275
MARCORY         2104
YAMOUSSOUKRO    2076
TREICHVILLE     2026
DALOA           1747
ATTECOUBE       1634
Name: CITY, dtype: int64

In [164]:

#Most used Region for the three days
count = dfnew['REGION'].value_counts()
count

#Region that was most active LEGUNE with BAFING being the list

LAGUNE               32960
LACS                  2408
BAS SASSANDRA         2327
HAUT SASSANDRA        2286
VALLEE DU BANDAMA     1551
SUD BANDAMA           1518
SAVANE                 999
18 MONTAGNES           936
FROMAGER               904
WORODOUGOU             792
MARAHOUE               618
AGNEBY                 583
NZI COMOE              564
MOYEN CAVALLY          528
DENGUELE               395
ZANZAN                 330
MOYEN COMOE            315
SUD COMOE              205
BAFING                  99
Name: REGION, dtype: int64

In [170]:
# The time mostly recorded
count = dfnew['DATE_TIME'].value_counts()
count.head(50)

2012-05-09 00:01:14.0    314
2012-05-09 00:00:05.0    309
2012-05-09 00:00:07.0    282
2012-05-09 00:00:11.0    276
2012-05-08 00:00:05.0    276
2012-05-09 00:00:03.0    253
2012-05-09 00:00:14.0    250
2012-05-09 00:00:04.0    242
2012-05-09 00:00:35.0    238
2012-05-08 00:00:44.0    237
2012-05-09 00:00:08.0    236
2012-05-09 00:00:27.0    234
2012-05-09 00:00:10.0    230
2012-05-09 00:00:23.0    229
2012-05-09 00:00:19.0    227
2012-05-09 00:00:01.0    225
2012-05-09 00:01:20.0    223
2012-05-08 00:01:14.0    223
2012-05-07 00:00:05.0    223
2012-05-09 00:00:57.0    221
2012-05-09 00:00:30.0    219
2012-05-09 00:01:21.0    216
2012-05-09 00:00:33.0    215
2012-05-09 00:00:52.0    214
2012-05-09 00:00:43.0    214
2012-05-07 00:00:10.0    213
2012-05-07 00:00:09.0    211
2012-05-08 00:00:10.0    211
2012-05-07 00:00:06.0    211
2012-05-09 00:00:12.0    211
2012-05-09 00:00:09.0    210
2012-05-09 00:00:47.0    209
2012-05-09 00:00:06.0    206
2012-05-09 00:01:40.0    206
2012-05-09 00:00:38.0    205
2012-05-08 00:01:03.0    205
2012-05-07 00:01:41.0    204
2012-05-09 00:00:18.0    203
2012-05-08 00:00:09.0    202
2012-05-08 00:00:01.0    200
2012-05-07 00:00:35.0    199
2012-05-08 00:01:27.0    197
2012-05-09 00:00:15.0    197
2012-05-08 00:00:52.0    196
2012-05-09 00:00:13.0    196
2012-05-08 00:00:22.0    196
2012-05-09 00:00:31.0    195
2012-05-07 00:00:20.0    195
2012-05-09 00:01:05.0    194
2012-05-09 00:00:20.0    194
Name: DATE_TIME, dtype: int64

In [147]:
#creating a pivot table
pd.pivot_table(dfnew, index=['DATE_TIME','CITY'], aggfunc='mean').head(25)

                                     LATITUDE  LONGITUDE   Unnamed: 0  \
DATE_TIME             CITY
2012-05-07 00:00:00.0 ABOBO          5.430472  -4.015944  1319.750000
                      BOUAKE         7.718417  -5.027139   974.500000
                      COCODY         5.351472  -3.966944  2536.000000
                      DAOUKRO        7.055778  -3.961083  1282.000000
                      GNAGBODOUGNOA  5.964111  -5.847750  1706.000000
                      ISSIA          6.495472  -6.579083  1885.500000
                      KORHOGO        9.443611  -5.617333  2073.000000
                      KOUIBLY        7.256722  -7.228611  2123.000000
                      KOUMASSI       5.293756  -3.960168  2147.000000
                      MAN            7.412243  -7.548759  2336.000000
                      MARCORY        5.284117  -3.969928  2678.500000
                      PLATEAU        5.338694  -4.021806  1864.500000
                      PONANGUIGLO    6.406747  -7.548556  2878.000000
                      YAMOUSSOUKRO   6.806875  -5.262653  2010.000000
                      YOPOUGON       5.334531  -4.090097  1525.437500
2012-05-07 00:00:01.0 ABOBO          5.420014  -4.015715   203.500000
                      ADJAME         5.359472  -4.023407  1975.666667
                      ATTECOUBE      5.351833  -4.041778  2236.000000
                      COCODY         5.359189  -3.970950   759.000000
                      DALOA          6.872306  -6.464833  1246.500000
                      DAOUKRO        7.055778  -3.961083  1282.000000
                      DIMBOKRO       6.657028  -4.722389  1371.500000
                      DUEKOUE        6.741000  -7.342194  1512.000000
                      GUIGLO         6.540667  -7.504278  1800.000000
                      HIRE           6.198472  -5.286222  1834.000000

                                          VALUE
DATE_TIME             CITY
2012-05-07 00:00:00.0 ABOBO            0.000000
                      BOUAKE           0.000000
                      COCODY           0.000000
                      DAOUKRO         38.000000
                      GNAGBODOUGNOA    0.000000
                      ISSIA           25.000000
                      KORHOGO          0.000000
                      KOUIBLY          0.000000
                      KOUMASSI        17.000000
                      MAN              0.000000
                      MARCORY          2.400000
                      PLATEAU          0.000000
                      PONANGUIGLO      0.000000
                      YAMOUSSOUKRO    30.000000
                      YOPOUGON         0.000000
2012-05-07 00:00:01.0 ABOBO           15.000000
                      ADJAME          14.166667
                      ATTECOUBE        0.000000
                      COCODY          20.600000
                      DALOA           84.000000
                      DAOUKRO        388.000000
                      DIMBOKRO        25.000000
                      DUEKOUE          9.000000
                      GUIGLO         766.000000
                      HIRE            42.000000

In [168]:
dfnew.pivot_table(index=['DATE_TIME','CITY'], aggfunc='count').head(50)

                                     AREA  CELL_ID_x  CELL_ID_y  CELL_ON_SITE  \
DATE_TIME             CITY
2012-05-07 00:00:00.0 ABOBO            12         12         12            12
                      BOUAKE            6          6          6             6
                      COCODY            3          3          3             3
                      DAOUKRO           6          6          6             6
                      GNAGBODOUGNOA     3          3          3             3
                      ISSIA             6          6          6             6
                      KORHOGO           3          3          3             3
                      KOUIBLY           3          3          3             3
                      KOUMASSI         12         12         12            12
                      MAN               9          9          9             9
                      MARCORY          10         10         10            10
                      PLATEAU           6          6          6             6
                      PONANGUIGLO       3          3          3             3
                      YAMOUSSOUKRO     12         12         12            12
                      YOPOUGON         16         16         16            16
2012-05-07 00:00:01.0 ABOBO             8          8          8             8
                      ADJAME           18         18         18            18
                      ATTECOUBE        12         12         12            12
                      COCODY           15         15         15            15
                      DALOA             6          6          6             6
                      DAOUKRO           6          6          6             6
                      DIMBOKRO          4          4          4             4
                      DUEKOUE           3          3          3             3
                      GUIGLO            3          3          3             3
                      HIRE              3          3          3             3
                      KONI              3          3          3             3
                      KOUMASSI         12         12         12            12
                      MARCORY           6          6          6             6
                      NAPIE             3          3          3             3
                      ODIENNE           3          3          3             3
                      PORT-BOUET        8          8          8             8
                      SAN-PEDRO         6          6          6             6
                      TAI               3          3          3             3
                      TOUMODI           4          4          4             4
                      TREICHVILLE       6          6          6             6
                      VAVOUA            6          6          6             6
                      YAMOUSSOUKRO      9          9          9             9
                      YOPOUGON         27         27         27            27
                      ZAGNE             3          3          3             3
2012-05-07 00:00:02.0 ABENGOUROU        3          3          3             3
                      ABOBO            14         18         18            18
                      BAHOMPA           3          3          3             3
                      BOUAKE            3          3          3             3
                      COCODY           15         15         15            15
                      DIVO             12         12         12            12
                      DUEKOUE           6          6          6             6
                      KONEDOUGOU        3          3          3             3
                      MARCORY           6          6          6             6
                      SAN-PEDRO         6          6          6             6
                      YAMOUSSOUKRO      6          6          6             6

                                     COUNTRY_A  COUNTRY_B  DECOUPZONE  \
DATE_TIME             CITY
2012-05-07 00:00:00.0 ABOBO                 12         12          12
                      BOUAKE                 6          6           6
                      COCODY                 3          3           3
                      DAOUKRO                6          6           6
                      GNAGBODOUGNOA          3          3           3
                      ISSIA                  6          6           6
                      KORHOGO                3          3           3
                      KOUIBLY                3          3           3
                      KOUMASSI              12         12          12
                      MAN                    9          9           9
                      MARCORY               10         10          10
                      PLATEAU                6          6           6
                      PONANGUIGLO            3          3           3
                      YAMOUSSOUKRO          12         12          12
                      YOPOUGON              16         16          16
2012-05-07 00:00:01.0 ABOBO                  8          8           8
                      ADJAME                18         18          18
                      ATTECOUBE             12         12          12
                      COCODY                15         15          15
                      DALOA                  6          6           6
                      DAOUKRO                6          6           6
                      DIMBOKRO               4          4           4
                      DUEKOUE                3          3           3
                      GUIGLO                 3          3           3
                      HIRE                   3          3           3
                      KONI                   3          3           3
                      KOUMASSI              12         12          12
                      MARCORY                6          6           6
                      NAPIE                  3          3           3
                      ODIENNE                3          3           3
                      PORT-BOUET             8          8           8
                      SAN-PEDRO              6          6           6
                      TAI                    3          3           3
                      TOUMODI                4          4           4
                      TREICHVILLE            6          6           6
                      VAVOUA                 6          6           6
                      YAMOUSSOUKRO           9          9           9
                      YOPOUGON              27         27          27
                      ZAGNE                  3          3           3
2012-05-07 00:00:02.0 ABENGOUROU             3          3           3
                      ABOBO                 18         18          18
                      BAHOMPA                3          3           3
                      BOUAKE                 3          3           3
                      COCODY                15         15          15
                      DIVO                  12         12          12
                      DUEKOUE                6          6           6
                      KONEDOUGOU             3          3           3
                      MARCORY                6          6           6
                      SAN-PEDRO              6          6           6
                      YAMOUSSOUKRO           6          6           6

                                     DW_A_NUMBER_INT  DW_B_NUMBER_INT  \
DATE_TIME             CITY
2012-05-07 00:00:00.0 ABOBO                       12               12
                      BOUAKE                       6                6
                      COCODY                       3                3
                      DAOUKRO                      6                6
                      GNAGBODOUGNOA                3                3
                      ISSIA                        6                6
                      KORHOGO                      3                3
                      KOUIBLY                      3                3
                      KOUMASSI                    12               12
                      MAN                          9                9
                      MARCORY                     10               10
                      PLATEAU                      6                6
                      PONANGUIGLO                  3                3
                      YAMOUSSOUKRO                12               12
                      YOPOUGON                    16               16
2012-05-07 00:00:01.0 ABOBO                        8                8
                      ADJAME                      18               18
                      ATTECOUBE                   12               12
                      COCODY                      15               15
                      DALOA                        6                6
                      DAOUKRO                      6                6
                      DIMBOKRO                     4                4
                      DUEKOUE                      3                3
                      GUIGLO                       3                3
                      HIRE                         3                3
                      KONI                         3                3
                      KOUMASSI                    12               12
                      MARCORY                      6                6
                      NAPIE                        3                3
                      ODIENNE                      3                3
                      PORT-BOUET                   8                8
                      SAN-PEDRO                    6                6
                      TAI                          3                3
                      TOUMODI                      4                4
                      TREICHVILLE                  6                6
                      VAVOUA                       6                6
                      YAMOUSSOUKRO                 9                9
                      YOPOUGON                    27               27
                      ZAGNE                        3                3
2012-05-07 00:00:02.0 ABENGOUROU                   3                3
                      ABOBO                       18               18
                      BAHOMPA                      3                3
                      BOUAKE                       3                3
                      COCODY                      15               15
                      DIVO                        12               12
                      DUEKOUE                      6                6
                      KONEDOUGOU                   3                3
                      MARCORY                      6                6
                      SAN-PEDRO                    6                6
                      YAMOUSSOUKRO                 6                6

                                     LATITUDE  LOCALISATION  LONGITUDE  \
DATE_TIME             CITY
2012-05-07 00:00:00.0 ABOBO                12            12         12
                      BOUAKE                6             6          6
                      COCODY                3             3          3
                      DAOUKRO               6             6          6
                      GNAGBODOUGNOA         3             3          3
                      ISSIA                 6             6          6
                      KORHOGO               3             3          3
                      KOUIBLY               3             3          3
                      KOUMASSI             12            12         12
                      MAN                   9             9          9
                      MARCORY              10            10         10
                      PLATEAU               6             6          6
                      PONANGUIGLO           3             3          3
                      YAMOUSSOUKRO         12            12         12
                      YOPOUGON             16            16         16
2012-05-07 00:00:01.0 ABOBO                 8             8          8
                      ADJAME               18            18         18
                      ATTECOUBE            12            12         12
                      COCODY               15            15         15
                      DALOA                 6             6          6
                      DAOUKRO               6             6          6
                      DIMBOKRO              4             4          4
                      DUEKOUE               3             3          3
                      GUIGLO                3             3          3
                      HIRE                  3             3          3
                      KONI                  3             3          3
                      KOUMASSI             12            12         12
                      MARCORY               6             6          6
                      NAPIE                 3             3          3
                      ODIENNE               3             3          3
                      PORT-BOUET            8             8          8
                      SAN-PEDRO             6             6          6
                      TAI                   3             3          3
                      TOUMODI               4             4          4
                      TREICHVILLE           6             6          6
                      VAVOUA                6             6          6
                      YAMOUSSOUKRO          9             9          9
                      YOPOUGON             27            27         27
                      ZAGNE                 3             3          3
2012-05-07 00:00:02.0 ABENGOUROU            3             3          3
                      ABOBO                18            18         18
                      BAHOMPA               3             3          3
                      BOUAKE                3             3          3
                      COCODY               15            15         15
                      DIVO                 12            12         12
                      DUEKOUE               6             6          6
                      KONEDOUGOU            3             3          3
                      MARCORY               6             6          6
                      SAN-PEDRO             6             6          6
                      YAMOUSSOUKRO          6             6          6

                                     PRODUCT  REGION  SITE_ID  STATUS  \
DATE_TIME             CITY
2012-05-07 00:00:00.0 ABOBO               12      12       12      12
                      BOUAKE               6       6        6       6
                      COCODY               3       3        3       3
                      DAOUKRO              6       6        6       6
                      GNAGBODOUGNOA        3       3        3       3
                      ISSIA                6       6        6       6
                      KORHOGO              3       3        3       3
                      KOUIBLY              3       3        3       3
                      KOUMASSI            12      12       12      12
                      MAN                  9       9        9       6
                      MARCORY             10      10       10      10
                      PLATEAU              6       6        6       6
                      PONANGUIGLO          3       3        3       3
                      YAMOUSSOUKRO        12      12       12      12
                      YOPOUGON            16      16       16      15
2012-05-07 00:00:01.0 ABOBO                8       8        8       8
                      ADJAME              18      18       18      17
                      ATTECOUBE           12      12       12      12
                      COCODY              15      15       15      15
                      DALOA                6       6        6       6
                      DAOUKRO              6       6        6       6
                      DIMBOKRO             4       4        4       4
                      DUEKOUE              3       3        3       3
                      GUIGLO               3       3        3       3
                      HIRE                 3       3        3       3
                      KONI                 3       3        3       3
                      KOUMASSI            12      12       12      12
                      MARCORY              6       6        6       6
                      NAPIE                3       3        3       3
                      ODIENNE              3       3        3       3
                      PORT-BOUET           8       8        8       8
                      SAN-PEDRO            6       6        6       6
                      TAI                  3       3        3       3
                      TOUMODI              4       4        4       4
                      TREICHVILLE          6       6        6       6
                      VAVOUA               6       6        6       6
                      YAMOUSSOUKRO         9       9        9       9
                      YOPOUGON            27      27       27      26
                      ZAGNE                3       3        3       3
2012-05-07 00:00:02.0 ABENGOUROU           3       3        3       3
                      ABOBO               18      18       18      18
                      BAHOMPA              3       3        3       3
                      BOUAKE               3       3        3       3
                      COCODY              15      15       15      15
                      DIVO                12      12       12      12
                      DUEKOUE              6       6        6       6
                      KONEDOUGOU           3       3        3       3
                      MARCORY              6       6        6       6
                      SAN-PEDRO            6       6        6       6
                      YAMOUSSOUKRO         6       6        6       6

                                     Unnamed: 0  VALUE  ZONENAME
DATE_TIME             CITY
2012-05-07 00:00:00.0 ABOBO                  12     12        12
                      BOUAKE                  6      6         6
                      COCODY                  3      3         3
                      DAOUKRO                 6      6         6
                      GNAGBODOUGNOA           3      3         3
                      ISSIA                   6      6         6
                      KORHOGO                 3      3         3
                      KOUIBLY                 3      3         3
                      KOUMASSI               12     12        12
                      MAN                     9      9         9
                      MARCORY                10     10        10
                      PLATEAU                 6      6         6
                      PONANGUIGLO             3      3         3
                      YAMOUSSOUKRO           12     12        12
                      YOPOUGON               16     16        16
2012-05-07 00:00:01.0 ABOBO                   8      8         8
                      ADJAME                 18     18        18
                      ATTECOUBE              12     12        12
                      COCODY                 15     15        15
                      DALOA                   6      6         6
                      DAOUKRO                 6      6         6
                      DIMBOKRO                4      4         4

In [180]:
#The most used product
count = dfnew['PRODUCT'].value_counts()
count.head(50)

# The most used product is the sms

sms      30292
Voice    22307
data      2230
Name: PRODUCT, dtype: int64

In [185]:
#Finding out the average value of product

#print(dfnew["VALUE"].min())
#print(dfnew["VALUE"].max())
print(dfnew["VALUE"].mean())
#minnimun value of product used was 0 while the maximum value of used product amounted to 12900.
#The mean value of product is 27.111

27.112586405004652